name: Publish Pages
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  deploy:
    permissions: { pages: write, id-token: write }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with: { path: site }
      - uses: actions/deploy-pages@v4
